export const themes = {
  light: [
    {
      value: "light-normal",
      label: "Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-black",
        nameBg: "bg-black",
        nameText: "text-white",
        buttonText: "text-white",
        avatarBg: "bg-black",
      },
    },
    {
      value: "light-blue",
      label: "Azul Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-blue-600",
        nameBg: "bg-blue-100",
        nameText: "text-blue-700",
        buttonText: "text-white",
        avatarBg: "bg-blue-500",
      },
    },
    {
      value: "light-green",
      label: "Verde Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-green-600",
        nameBg: "bg-green-100",
        nameText: "text-green-700",
        buttonText: "text-white",
        avatarBg: "bg-green-500",
      },
    },
    {
      value: "light-purple",
      label: "Roxo Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-purple-600",
        nameBg: "bg-purple-100",
        nameText: "text-purple-700",
        buttonText: "text-white",
        avatarBg: "bg-purple-500",
      },
    },
    {
      value: "light-orange",
      label: "Laranja Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-orange-600",
        nameBg: "bg-orange-100",
        nameText: "text-orange-700",
        buttonText: "text-white",
        avatarBg: "bg-orange-500",
      },
    },
    {
      value: "light-red",
      label: "Vermelho Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-red-600",
        nameBg: "bg-red-100",
        nameText: "text-red-700",
        buttonText: "text-white",
        avatarBg: "bg-red-500",
      },
    },
    {
      value: "light-pink",
      label: "Rosa Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-pink-600",
        nameBg: "bg-pink-100",
        nameText: "text-pink-700",
        buttonText: "text-white",
        avatarBg: "bg-pink-500",
      },
    },
    {
      value: "light-gradient-blue",
      label: "Gradiente Azul Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-gradient-to-r from-blue-500 to-blue-700",
        nameBg: "bg-blue-100",
        nameText: "text-blue-700",
        buttonText: "text-white",
        avatarBg: "bg-gradient-to-br from-blue-400 to-blue-600",
      },
    },
    {
      value: "light-gradient-pink",
      label: "Gradiente Rosa Claro",
      styles: {
        background: "bg-white",
        text: "text-black",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-gradient-to-r from-pink-500 to-pink-700",
        nameBg: "bg-pink-100",
        nameText: "text-pink-700",
        buttonText: "text-white",
        avatarBg: "bg-gradient-to-br from-pink-400 to-pink-600",
      },
    },
  ],
  dark: [
    {
      value: "dark-blue",
      label: "Azul Escuro",
      styles: {
        background: "bg-zinc-900",
        text: "text-white",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-blue-700",
        nameBg: "bg-blue-900/20",
        nameText: "text-blue-500",
        buttonText: "text-white",
        avatarBg: "bg-blue-600",
      },
    },
    {
      value: "dark-green",
      label: "Verde Escuro",
      styles: {
        background: "bg-zync-950",
        text: "text-white",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-green-700",
        nameBg: "bg-green-900/10",
        nameText: "text-green-500",
        buttonText: "text-white",
        avatarBg: "bg-green-600",
      },
    },
    {
      value: "dark-purple",
      label: "Roxo Escuro",
      styles: {
        background: "bg-zync-950",
        text: "text-white",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-purple-700",
        nameBg: "bg-purple-900/20",
        nameText: "text-purple-500",
        buttonText: "text-white",
        avatarBg: "bg-purple-600",
      },
    },
    {
      value: "dark-red",
      label: "Vermelho Escuro",
      styles: {
        background: "bg-zync-950",
        text: "text-white",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-red-700",
        nameBg: "bg-red-900/20",
        nameText: "text-red-600",
        buttonText: "text-white",
        avatarBg: "bg-red-600",
      },
    },
    {
      value: "dark-orange",
      label: "Laranja Escuro",
      styles: {
        background: "bg-zync-950",
        text: "text-white",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-orange-700",
        nameBg: "bg-orange-900/20",
        nameText: "text-orange-500",
        buttonText: "text-white",
        avatarBg: "bg-orange-600",
      },
    },
    {
      value: "dark-gray",
      label: "Cinza Escuro",
      styles: {
        background: "bg-zync-950",
        text: "text-white",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-gray-700",
        nameBg: "bg-gray-800/20",
        nameText: "text-gray-500",
        buttonText: "text-white",
        avatarBg: "bg-gray-600",
      },
    },
    {
      value: "dark-gradient-red",
      label: "Gradiente Vermelho Escuro",
      styles: {
        background: "bg-zync-950",
        text: "text-white",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-gradient-to-r from-red-600 to-red-800",
        nameBg: "bg-red-900/20",
        nameText: "text-red-500",
        buttonText: "text-white",
        avatarBg: "bg-gradient-to-br from-red-500 to-red-700",
      },
    },
    {
      value: "dark-gradient-gray",
      label: "Gradiente Cinza Escuro",
      styles: {
        background: "bg-zync-950",
        text: "text-white",
        mutedText: "text-muted-foreground",
        buttonBg: "bg-gradient-to-r from-muted to-muted/80",
        nameBg: "bg-muted/80",
        nameText: "text-muted-foreground",
        buttonText: "text-white",
        avatarBg: "bg-gradient-to-br from-muted to-muted/80",
      },
    },
  ],
};
