export const themes = {
  light: {
    background: "bg-white",
    text: "text-black",
    mutedText: "text-muted-foreground",
    buttonBg: "bg-primary",
    nameBg: "bg-primary/20",
    nameText: "text-primary",
    buttonText: "text-white",
    avatarBg: "bg-primary",
  },
  dark: {
    background: "bg-zinc-950",
    text: "text-white",
    mutedText: "text-muted-foreground",
    buttonBg: "bg-primary",
    nameBg: "bg-primary/20",
    nameText: "text-primary",
    buttonText: "text-white",
    avatarBg: "bg-primary",
  },
  blue: {
    background: "bg-zinc-950",
    text: "text-white",
    mutedText: "text-muted-foreground",
    nameBg: "bg-blue-700/20",
    nameText: "text-blue-500",
    buttonBg: "bg-blue-700",
    buttonText: "text-white",
    avatarBg: "bg-blue-600",
  },
  green: {
    background: "bg-zinc-950",
    text: "text-white",
    mutedText: "text-muted-foreground",
    nameBg: "bg-green-700/20",
    nameText: "text-green-500",
    buttonBg: "bg-green-700",
    buttonText: "text-white",
    avatarBg: "bg-green-600",
  },
};
